name: Comment on New Issue or PR

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    permissions:
      issues: write         # Needed to comment on issues and PRs

    steps:
    - name: Post a comment
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: "Note: This issue will be automatically closed shortly. For review and assistance resolution Please comment your contact e-mail address to enable support reach out to you"
          });
